
INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Joomla games game','com_jugb_joomla_games.joomlagamesgame','{"special":{"dbtable":"#__jugb_joomla_games_games","key":"id","type":"Joomlagamesgame","prefix":"Jugb_joomla_gamesTable"}}', '{"formFile":"administrator\/components\/com_jugb_joomla_games\/models\/forms\/joomlagamesgame.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_jugb_joomla_games.joomlagamesgame')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Joomla games game', 
	`table` = '{"special":{"dbtable":"#__jugb_joomla_games_games","key":"id","type":"Joomla games game","prefix":"Jugb_joomla_gamesTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_jugb_joomla_games\/models\/forms\/joomlagamesgame.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_jugb_joomla_games.joomlagamesgame');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Joomla games score','com_jugb_joomla_games.joomlagamesscore','{"special":{"dbtable":"#__jugb_joomla_games_score","key":"id","type":"Joomlagamesscore","prefix":"Jugb_joomla_gamesTable"}}', '{"formFile":"administrator\/components\/com_jugb_joomla_games\/models\/forms\/joomlagamesscore.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"uid","targetTable":"users","targetColumn":"users_id","displayColumn":"users_username"},{"sourceColumn":"gid","targetTable":"#__jugb_joomla_games_games","targetColumn":"id","displayColumn":"name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_jugb_joomla_games.joomlagamesscore')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Joomla games score', 
	`table` = '{"special":{"dbtable":"#__jugb_joomla_games_score","key":"id","type":"Joomla games score","prefix":"Jugb_joomla_gamesTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_jugb_joomla_games\/models\/forms\/joomlagamesscore.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"uid","targetTable":"users","targetColumn":"users_id","displayColumn":"users_username"},{"sourceColumn":"gid","targetTable":"#__jugb_joomla_games_games","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_jugb_joomla_games.joomlagamesscore');
